config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  resources :products do
    match '/scrape', to: 'products#scrape', via: :post, on: :collection
  end

  root to: 'products#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
end

app/models/products_spider.rb
require 'kimurai'
require 'net/http'
require 'open-uri'
require 'webdrivers'

class ProductsSpider < Kimurai::Base
  @name = 'products_spider'
  @engine = :selenium_chrome
  @start_urls = ['https://www.amazon.com/s?k=motherboard']
  @config = {
    user_agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36',
    before_request: { delay: 4..7 }
  }

  def parse(response, url:, data: {})
    response.xpath("/html/body/div[1]/div[2]/div[1]/div/div[1]").each do |a|
      request_to :parse_repo_page, url: absolute_url(a[:href], base: url)
    end

    if next_page = response.at_xpath("/html/body/div[1]/div[2]/div[1]/div/div[1]/div/span[3]/div[2]/div[23]/span/div/div/ul/li[7]")
      request_to :parse, url: absolute_url(next_page[:href], base: url)
    end
  end

  def parse_repo_page(response, url:, data: {})
    item = {}

    item[:item_name] = response.xpath("/html/body/div[1]/div[2]/div[1]/div/div[1]/div/span[3]/div[2]/div[2]/div/span/div/div/div[2]/div[2]/div/div/div[1]/h2").text
    item[:item_description] = response.xpath("/html/body/div[1]/div[2]/div[1]/div/div[1]/div/span[3]/div[2]/div[2]/div/span/div/div/div[2]/div[2]/div/div/div[3]/div[1]/div/div[1]/div/a").text
    
    save_to "results.json", item, format: :pretty_json
  end
end

app/models/web_scraper.rb
require 'kimurai'

class WebScrapper < Kimurai::Base
  @name = "web_scrapper_spider"
  @engine = :selenium_chrome
  @start_urls = ["https://metaruby.com/"]
  @config = {
      user_agent: "Chrome/68.0.3440.84"
    }

  attr_accessor :blogs

  def parse(response, url:, data: { })
    @blogs = []
    posts_headers_path = "//table[@class='topic-list ember-view']//tbody//tr"
    count = response.xpath(posts_headers_path).count
    
    loop do
      browser.execute_script("window.scrollBy(0,10000)") ; sleep 2
      response = browser.current_response

      new_count = response.xpath(posts_headers_path).count
      if count == new_count
        parse_data(response)
        logger.info "> Pagination is done" and break
      else
        count = new_count
        logger.info "> Continue scrolling, current count is #{count}..."
      end
    end
    
    logger.info "> Data saved to results.json"
  end

  def parse_data(response)
    response.xpath("//table[@class='topic-list ember-view']//tbody//tr").each do |tr|
      scrapped_data = {
                        title: tr.at('td[1]//span').text,
                        category: tr.at('td[1]//div//span').text,
                        date: tr.at('td[3]').text.strip
                      }
      blogs << scrapped_data
      save_to "results.json", scrapped_data.as_json, format: :json
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  #before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  def scrape
    url = 'https://lazada.com.ph/'
    response = ProductsSpider.process(url)
    if response[:status] == :completed && response[:error].nil?
      flash.now[:notice] = 'Successfully scraped url'
    else
      flash.now[:alert] = response[:error]
    end
  rescue StandardError => e
    flash.now[:alert] = "Error: #{e}"
  end

  # GET /products/1 or /products/1.json
  def show
    @products = Product.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        render :new
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:item_name, :item_image, :item_rating, :price, :store, :item_description,
                                    :item_brand, :item_model, :sku, :display_size, :Processor_type, :model, :warranty)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  # before_action :set_vehicle, only: %i[ show edit update destroy ]

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  def scrape
    url = 'https://www.cars.com/shopping/sedan/'
    response = VehiclesSpider.process(url)
    if response[:status] == :completed && response[:error].nil?
      flash.now[:notice] = "Successfully scraped url"
    else
      flash.now[:alert] = response[:error]
    end
  rescue StandardError => e
    flash.now[:alert] = "Error: #{e}"
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show
    @vehicles = Vehicle.all
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: "Vehicle was successfully created." }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: "Vehicle was successfully updated." }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: "Vehicle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_vehicle
    #   @vehicle = Vehicle.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit(:title, :stock_type, :exterior_color, :interior_color, :transmission, :drivetrain, :price, :miles)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/web_scrappers_helper.rb
module WebScrappersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScraper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_name %>
    <%= form.text_field :item_name %>
  </div>

  <div class="field">
    <%= form.label :item_image %>
    <%= form.text_field :item_image %>
  </div>

  <div class="field">
    <%= form.label :item_rating %>
    <%= form.text_field :item_rating %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :store %>
    <%= form.text_field :store %>
  </div>

  <div class="field">
    <%= form.label :item_description %>
    <%= form.text_field :item_description %>
  </div>

  <div class="field">
    <%= form.label :item_brand %>
    <%= form.text_field :item_brand %>
  </div>

  <div class="field">
    <%= form.label :item_model %>
    <%= form.text_field :item_model %>
  </div>

  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku %>
  </div>

  <div class="field">
    <%= form.label :display_size %>
    <%= form.text_field :display_size %>
  </div>

  <div class="field">
    <%= form.label :Processor_type %>
    <%= form.text_field :Processor_type %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :warranty %>
    <%= form.number_field :warranty %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= button_to 'Scrape', scrape_products_path %>
<%= button_to 'Scrape GH', scrape_products_path %>

<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Item name</th>
      <th>Item image</th>
      <th>Item rating</th>
      <th>Price</th>
      <th>Store</th>
      <th>Item description</th>
      <th>Item brand</th>
      <th>Item model</th>
      <th>Sku</th>
      <th>Display size</th>
      <th>Processor type</th>
      <th>Model</th>
      <th>Warranty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.item_name %></td>
        <td><%= product.item_image %></td>
        <td><%= product.item_rating %></td>
        <td><%= product.price %></td>
        <td><%= product.store %></td>
        <td><%= product.item_description %></td>
        <td><%= product.item_brand %></td>
        <td><%= product.item_model %></td>
        <td><%= product.sku %></td>
        <td><%= product.display_size %></td>
        <td><%= product.Processor_type %></td>
        <td><%= product.model %></td>
        <td><%= product.warranty %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.item_name %></td>
        <td><%= product.item_image %></td>
        <td><%= product.item_rating %></td>
        <td><%= product.price %></td>
        <td><%= product.store %></td>
        <td><%= product.item_description %></td>
        <td><%= product.item_brand %></td>
        <td><%= product.item_model %></td>
        <td><%= product.sku %></td>
        <td><%= product.display_size %></td>
        <td><%= product.Processor_type %></td>
        <td><%= product.model %></td>
        <td><%= product.warranty %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :stock_type %>
    <%= form.text_field :stock_type %>
  </div>

  <div class="field">
    <%= form.label :exterior_color %>
    <%= form.text_field :exterior_color %>
  </div>

  <div class="field">
    <%= form.label :interior_color %>
    <%= form.text_field :interior_color %>
  </div>

  <div class="field">
    <%= form.label :transmission %>
    <%= form.text_field :transmission %>
  </div>

  <div class="field">
    <%= form.label :drivetrain %>
    <%= form.text_field :drivetrain %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :miles %>
    <%= form.number_field :miles %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<%= button_to 'Scrape', scrape_vehicles_path %>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Stock type</th>
      <th>Exterior color</th>
      <th>Interior color</th>
      <th>Transmission</th>
      <th>Drivetrain</th>
      <th>Price</th>
      <th>Miles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.title %></td>
        <td><%= vehicle.stock_type %></td>
        <td><%= vehicle.exterior_color %></td>
        <td><%= vehicle.interior_color %></td>
        <td><%= vehicle.transmission %></td>
        <td><%= vehicle.drivetrain %></td>
        <td><%= vehicle.price %></td>
        <td><%= vehicle.miles %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/scrape.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<%= link_to 'Go Back', root_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.title %></td>
        <td><%= vehicle.stock_type %></td>
        <td><%= vehicle.exterior_color %></td>
        <td><%= vehicle.interior_color %></td>
        <td><%= vehicle.transmission %></td>
        <td><%= vehicle.drivetrain %></td>
        <td><%= vehicle.price %></td>
        <td><%= vehicle.miles %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>